version: '3.1'

services:
  db:
    image: postgres:13.4
    privileged: true
    ports:
    - 24322:5432
    environment:
      POSTGRES_USER: gogi
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: todo
