version: '3.1'

services:
  db:
    image: postgres:13.4
    privileged: true
    ports:
    - 24322:5432
    environment:
      POSTGRES_USER: gogi
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: todo

  backend:
    build: ./backend
    privileged: true
    ports:
      - 8080:8080
    command: bash -c "
        python manage.py migrate &&
        gunicorn backend.wsgi -b 0.0.0.0:8080
      "
    depends_on:
      - db
